Bajar el CSV de Oferta GastronÃ³mica desde Buenos Aires Data (https://data.buenosaires.gob.ar/dataset/). Idealmente hacer esto con Python.

In [9]:
import pandas as pd
import requests
import io

bajada = requests.get('https://cdn.buenosaires.gob.ar/datosabiertos/datasets/ente-de-turismo/oferta-establecimientos-gastronomicos/oferta_gastronomica.csv')
data = bajada.content.decode('utf-8')
df = pd.read_csv(io.StringIO(data), delimiter=',', decimal='.', encoding= 'utf-8') # El StringIO me trata la cadena como un archivo

# Los meto a una lista de tuplas para que los pueda mandar a la BD
entradas = [  ( str(row['nombre']), str(row['categoria']), str(row['direccion_completa']), str(row['barrio']), str(row['comuna'][7::]) ) for i, row in df.iterrows()]

Crear una tabla con los siguientes campos: id_local, nombre, categoria, direccion, barrio, comuna, para posteriormente poblarla con los datos bajados, utilzando el conector desde el script de Python.

In [10]:
import pymysql

conexion = pymysql.connect(
    host='localhost',
    database='test',
    user='root',
    password='root'
)
cursor = conexion.cursor()

# for entrada in entradas:
#     conexion.execute( "INSERT INTO gastronomia(nombre, categoria, direccion, barrio, comuna) VALUES (%s, %s, %s, %s, %s)", entrada)

query = "INSERT INTO gastronomia(nombre, categoria, direccion, barrio, comuna) VALUES (%s,%s,%s,%s,%s)"
cursor.executemany(query, entradas)

OperationalError: (1049, "Unknown database 'test'")

In [ ]:
conexion.commit()

In [ ]:
cursor.execute("SELECT * FROM gastronomia LIMIT 100")
cursor.fetchall()

((1,
  'GUANTANAMERA',
  'RESTAURANTE',
  'MOREAU DE JUSTO, ALICIA AV. 2092',
  'Puerto Madero',
  '1'),
 (2, '1843 VINACOTECA', 'VINERIA', 'HUMBERTO 1Âº 1843', 'San Cristobal', '3'),
 (3, '2080 EXPRESS', 'RESTAURANTE', 'JURAMENTO AV. 2080', 'Belgrano', '13'),
 (4, '22', 'CAFE', 'MURGUIONDO 4188', 'Villa Lugano', '8'),
 (5, '4 EN 2 I', 'RESTAURANTE', 'BORGES, JORGE LUIS 2095', 'Palermo', '14'),
 (6, '4 X 4 CAFE', 'BAR', 'DEL LIBERTADOR AV. 3838', 'Palermo', '14'),
 (7, '5TA AVENIDA', 'RESTAURANTE', 'SARMIENTO 814', 'San Nicolas', '1'),
 (8, '5TA AVENIDA I', 'RESTAURANTE', 'SARMIENTO 381', 'San Nicolas', '1'),
 (9, '5TA ZONA', 'nan', 'MURILLO 1049', 'Villa Crespo', '15'),
 (10, '650', 'RESTAURANTE', 'SAN MARTIN 650', 'San Nicolas', '1'),
 (11, '788 FOODBAR', 'RESTAURANTE', 'ARENALES 1877', 'Recoleta', '2'),
 (12, '7 SEVEN', 'RESTAURANTE', 'GORRITI 5802', 'Palermo', '14'),
 (13, '8 MILIMETROS', 'RESTAURANTE', 'GORRITI 5535', 'Palermo', '14'),
 (14,
  '9 DE JULIO',
  'RESTAURANTE',
  'PELLEGRINI, CARLOS 593',
  'San Nicolas',
  '1'),
 (15, '9 DE JULIO II', 'CAFE', 'RIESTRA AV. 5498', 'Villa Lugano', '8'),
 (16, 'ABC', 'RESTAURANTE', 'LAVALLE 545', 'San Nicolas', '1'),
 (17, 'ABRIL', 'RESTAURANTE', 'ARENALES 900', 'Retiro', '1'),
 (18, 'ABRIL BRISTO', 'RESTAURANTE', 'BALCARCE 722', 'San Telmo', '1'),
 (19, 'ABUELO MATIAS', 'RESTAURANTE', 'SAN PEDRITO 1094', 'Flores', '7'),
 (20, 'ACABAR', 'BAR', 'HONDURAS 5733', 'Palermo', '14'),
 (21, 'ACAPULCO', 'RESTAURANTE', 'LAVALLE 757', 'San Nicolas', '1'),
 (22, 'ACAPULCO', 'CAFE', 'MORENO 1800', 'Monserrat', '1'),
 (23,
  'ACCADEMIA della pizza',
  'RESTAURANTE',
  'TRIUNVIRATO AV. 4495',
  'Villa Urquiza',
  '12'),
 (24, 'A CORUÃÆÃ¢â¬ËA', 'VINERIA', 'MISIONES 125', 'Balvanera', '3'),
 (25, 'ACQUANOVA', 'nan', 'DIAZ, CNEL. AV. 1879', 'Recoleta', '2'),
 (26, 'ACROPOLIS', 'CAFE', 'CORDOBA AV. 3493', 'Recoleta', '2'),
 (27, 'ACUARIO', 'RESTAURANTE', 'VARELA AV. 920', 'Flores', '7'),
 (28, 'ADANN', 'RESTAURANTE', 'HERNANDEZ, JOSE 2345', 'Belgrano', '13'),
 (29, 'AFICHE', 'CAFE', 'ALVEAR, MARCELO T. De 2119', 'Recoleta', '2'),
 (30, 'A FUEGO LENTO', 'RESTAURANTE', 'SANTO TOME 5915', 'Versalles', '10'),
 (31, 'AGARRATE CATALINA', 'RESTAURANTE', 'CABOTO 537', 'Boca', '4'),
 (32, 'AGRAZ', 'RESTAURANTE', 'POSADAS 1232', 'Retiro', '1'),
 (33,
  'AIRES DE PATAGONIA',
  'RESTAURANTE',
  'MOREAU DE JUSTO, ALICIA AV. 1798',
  'Puerto Madero',
  '1'),
 (34,
  'A. J. JARDIN CERVERCERO',
  'RESTAURANTE',
  'CHILE AV. 342',
  'San Telmo',
  '1'),
 (35, 'ALA...', 'RESTAURANTE', 'BELGRANO AV. 1836', 'Balvanera', '3'),
 (36, 'ALABAMA', 'RESTAURANTE', 'RIVADAVIA AV. 3102', 'Balvanera', '3'),
 (37, 'ALABAMA', 'RESTAURANTE', 'SANTA FE AV. 5270', 'Palermo', '14'),
 (38, 'ALAI', 'CAFE', 'ALSINA, ADOLFO 1702', 'Monserrat', '1'),
 (39,
  'A LA MAROSKA',
  'RESTAURANTE',
  'ALVEAR, MARCELO T. De 2251',
  'Recoleta',
  '2'),
 (40, 'ALAMEDA', 'RESTAURANTE', 'DE MAYO AV. 1203', 'Monserrat', '1'),
 (41, 'ALAMEDA', 'RESTAURANTE', 'LAS HERAS GENERAL AV. 2324', 'Recoleta', '2'),
 (42, 'AL ANDALUZ', 'BAR', 'GODOY CRUZ 1823', 'Palermo', '14'),
 (43, 'ALARICO', 'RESTAURANTE', 'CHILE 518', 'San Telmo', '1'),
 (44, 'AL BAR', 'BAR', 'SAN JUAN AV. 915', 'Constitucion', '1'),
 (45, 'ALBERNIZ', 'CAFE', 'RIVADAVIA AV. 2886', 'Balvanera', '3'),
 (46, 'ALBOR', 'BAR', 'CALVO, CARLOS 819', 'Constitucion', '1'),
 (47, 'AL CLUB', 'RESTAURANTE', 'PARAGUAY 2044', 'Recoleta', '2'),
 (48, 'ALDEA DE ALBARICOQUE', 'RESTAURANTE', 'LAMBARE 847', 'Almagro', '5'),
 (49, 'ALEA', 'CAFE', 'TALCAHUANO 888', 'Retiro', '1'),
 (50, 'ALE- ALE', 'nan', 'ESTADO DE ISRAEL AV. 4503', 'Villa Crespo', '15'),
 (51, 'ALEKS', 'CAFE', 'CORDOBA AV. 1541', 'Recoleta', '2'),
 (52, 'ALEXANDER', 'RESTAURANTE', 'TUCUMAN 304', 'San Nicolas', '1'),
 (53, 'ALFONSO 1RO', 'RESTAURANTE', 'PARAGUAY 3948', 'Palermo', '14'),
 (54, 'ALFRED', 'RESTAURANTE', 'PUEYRREDON AV. 1335', 'Recoleta', '2'),
 (55, 'AL FRESCO', 'RESTAURANTE', 'HONDURAS 5201', 'Palermo', '14'),
 (56, 'ALGO NATURAL', 'RESTAURANTE', 'VIAMONTE 351', 'San Nicolas', '1'),
 (57,
  'ALHAMBRA',
  'RESTAURANTE',
  'RIVADAVIA AV. 8628',
  'Velez Sarsfield',
  '10'),
 (58, 'ALHARACA', 'RESTAURANTE', 'GORRITI 5045', 'Palermo', '14'),
 (59, 'ALIMENTAR', 'RESTAURANTE', 'SAN MARTIN 570', 'San Nicolas', '1'),
 (60, 'ALIMENTARI', 'RESTAURANTE', 'LAVALLE 1120', 'San Nicolas', '1'),
 (61, 'ALIMENTOS', 'RESTAURANTE', 'SARMIENTO 372', 'San Nicolas', '1'),
 (62, 'ALL VERDI', 'RESTAURANTE', 'OLIDEN 1493', 'Mataderos', '9'),
 (63,
  'ALMACEN NATURISTA',
  'RESTAURANTE',
  'MANSILLA, LUCIO NORBERTO, GENERAL 2740',
  'Recoleta',
  '2'),
 (64, 'ALMONTE', 'RESTAURANTE', 'BONPLAND 1939', 'Palermo', '14'),
 (65, 'ALO - ALO', 'RESTAURANTE', 'RIVADAVIA AV. 4945', 'Caballito', '6'),
 (66, 'ALPINA SKATE', 'PUB', 'RIVADAVIA AV. 6431', 'Flores', '7'),
 (67,
  'AL SHARK',
  'RESTAURANTE',
  'SCALABRINI ORTIZ, RAUL AV. 1426',
  'Palermo',
  '14'),
 (68, 'ALSINA 300', 'RESTAURANTE', 'ALSINA, ADOLFO 300', 'Monserrat', '1'),
 (69, 'AL TAGLIO PIZZORANTE', 'RESTAURANTE', 'ARAOZ 2476', 'Palermo', '14'),
 (70, 'ALTO GOYENO', 'RESTAURANTE', 'GOYENA, PEDRO AV. 599', 'Caballito', '6'),
 (71,
  'ALVEAR PARK',
  'RESTAURANTE',
  'ALBERDI, JUAN BAUTISTA AV. 4302',
  'Parque Avellaneda',
  '9'),
 (72, 'AMADEUS', 'PUB', 'RIVADAVIA AV. 7472', 'Flores', '7'),
 (73, 'AMAKAI', 'CAFE', 'INDEPENDENCIA AV. 3001', 'Balvanera', '3'),
 (74, 'AMARETTO', 'RESTAURANTE', 'CHORROARIN AV. 1206', 'Villa Ortuzar', '15'),
 (75,
  'AMBAR BUENOS AIRES',
  'PUB',
  'BEIRO, FRANCISCO AV. 3124',
  'Villa Del Parque',
  '11'),
 (76, 'AMERICA', 'RESTAURANTE', 'HIDALGO 899', 'Caballito', '6'),
 (77, 'AMERICA DELI', 'CAFE', 'PERU 85', 'Monserrat', '1'),
 (78, 'AMERICANO', 'BAR', 'BELGRANO AV. 1421', 'Monserrat', '1'),
 (79, 'AMICO', 'CAFE', 'CHILE 1110', 'Monserrat', '1'),
 (80,
  'AMIGOS',
  'BAR',
  'PERON, JUAN DOMINGO, TTE. GENERAL 1417',
  'San Nicolas',
  '1'),
 (81, 'AMIGOS PROPIETARIOS', 'RESTAURANTE', 'AYACUCHO 2183', 'Recoleta', '2'),
 (82, 'AMIKO', 'RESTAURANTE', 'LIMA 700', 'Monserrat', '1'),
 (83, 'ANAHI', 'BAR', 'ALEM, LEANDRO N. AV. 481', 'San Nicolas', '1'),
 (84, 'AÃÆÃ¢â¬ËARO CERO', 'CAFE', 'ALSINA, ADOLFO 1494', 'Monserrat', '1'),
 (85, 'ANCHORENA PLAZA', 'RESTAURANTE', 'SANTA FE AV. 2702', 'Recoleta', '2'),
 (86, 'ANDEN', 'RESTAURANTE', 'SANTA FE AV. 5302', 'Palermo', '14'),
 (87, 'ANGECINA', 'RESTAURANTE', 'REPUBLICA DOMINICANA 3386', 'Palermo', '14'),
 (88, 'ANGELIN', 'RESTAURANTE', 'CORDOBA AV. 5770', 'Chacarita', '15'),
 (89, 'ANGELINA', 'RESTAURANTE', 'CHARCAS 3386', 'Palermo', '14'),
 (90, "ANGELO'S", 'CAFE', 'SANTA FE AV. 2779', 'Recoleta', '2'),
 (91, 'ANGELUS', 'RESTAURANTE', 'DEL LIBERTADOR AV. 7598', 'NuÃÆÃÂ±ez', '13'),
 (92, 'ANGLO', 'CAFE', 'RIVADAVIA AV. 7510', 'Flores', '7'),
 (93, 'ANGOSTURA', 'RESTAURANTE', 'LAVALLE 400', 'San Nicolas', '1'),
 (94, 'ANIMATE', 'CAFE', 'RIVADAVIA AV. 7390', 'Flores', '7'),
 (95, 'ANITA', 'RESTAURANTE', 'NEWBERY, JORGE AV. 3902', 'Chacarita', '15'),
 (96, 'ANKER', 'RESTAURANTE', 'VIAMONTE 1602', 'San Nicolas', '1'),
 (97, 'ANTAÃÆÃ¢â¬ËO BAR', 'BAR', 'VUELTA DE OBLIGADO 1101', 'Palermo', '14'),
 (98, 'ANTE SALA', 'BAR', 'COSTA RICA 4969', 'Palermo', '14'),
 (99, 'ANUSH', 'BAR', 'ARMENIA 1242', 'Palermo', '14'),
 (100, 'APETECE', 'RESTAURANTE', 'PELLEGRINI, CARLOS 169', 'San Nicolas', '1'))

A partir de tener los datos disponibles, responder a las siguientes preguntas: a) Â¿CuÃ¡l es el barrio con mayor cantidad de Pubs? b) Obtener la cantidad de locales por categorÃ­a c) Obtener la cantidad de restaurantes por comuna

,long,lat,id,nombre,categoria,cocina,ambientacion,telefono,mail,horario,calle_nombre,calle_altura,calle_cruce,direccion_completa,barrio,comuna,codigo_postal,codigo_postal_argentino
0,-58.363307,-34.622963,1602,GUANTANAMERA,RESTAURANTE,CUBANA,MODERNO,4314 0770,NaN,NaN,MOREAU DE JUSTO ALICIA,2092,NaN,"MOREAU DE JUSTO, ALICIA AV. 2092",Puerto Madero,Comuna 1,1107.0,C1107AFP
1,-58.392330,-34.621554,676,1843 VINACOTECA,VINERIA,NaN,NaN,4779 0806,NaN,lunes a domingo de 8 a 00,HUMBERTO 1Âº,1843,NaN,HUMBERTO 1Âº 1843,San Cristobal,Comuna 3,NaN,NaN
2,-58.453542,-34.560311,487,2080 EXPRESS,RESTAURANTE,TRADICIONAL,CLASICO PORTEÃO,4788 4500,NaN,lunes a domingo de 8 a 00,JURAMENTO,2080,NaN,JURAMENTO AV. 2080,Belgrano,Comuna 13,1428.0,C1428DNH
3,-58.475491,-34.677051,2737,22,CAFE,MINUTAS,MODERNO,NaN,NaN,NaN,MURGUIONDO,4188,NaN,MURGUIONDO 4188,Villa Lugano,Comuna 8,1439.0,C1439FTB
4,-58.425437,-34.585695,2,4 EN 2 I,RESTAURANTE,NaN,NaN,4832 9510,NaN,NaN,BORGES JORGE LUIS,2095,NaN,"BORGES, JORGE LUIS 2095",Palermo,Comuna 14,1425.0,C1425FFA

Otros comandos:
cursor.execute('SELECT * FROM tabla)
variable = cursor.fetchall() --> Todos los registros
variable = cursor.fetchmany(N) --> N registros
variable = cursor.fetchone() --> un registro

conexion.rollback() --> no guardo los cambios